// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	order_grpc "github.com/rigmas/microservices/order/handlers/order_grpc"
)

// OrderServiceClient is an autogenerated mock type for the OrderServiceClient type
type OrderServiceClient struct {
	mock.Mock
}

// OrderList provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) OrderList(ctx context.Context, in *order_grpc.OrderListRequest, opts ...grpc.CallOption) (*order_grpc.OrderListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_grpc.OrderListResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_grpc.OrderListRequest, ...grpc.CallOption) *order_grpc.OrderListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_grpc.OrderListResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_grpc.OrderListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrderServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderServiceClient creates a new instance of OrderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderServiceClient(t mockConstructorTestingTNewOrderServiceClient) *OrderServiceClient {
	mock := &OrderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
