// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeOrderServiceServer is an autogenerated mock type for the UnsafeOrderServiceServer type
type UnsafeOrderServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedOrderServiceServer provides a mock function with given fields:
func (_m *UnsafeOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeOrderServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeOrderServiceServer creates a new instance of UnsafeOrderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeOrderServiceServer(t mockConstructorTestingTNewUnsafeOrderServiceServer) *UnsafeOrderServiceServer {
	mock := &UnsafeOrderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
