// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	product_grpc "github.com/rigmas/microservices/product/handlers/product_grpc"
)

// ProductServiceClient is an autogenerated mock type for the ProductServiceClient type
type ProductServiceClient struct {
	mock.Mock
}

// ProductList provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) ProductList(ctx context.Context, in *product_grpc.ProductListRequest, opts ...grpc.CallOption) (*product_grpc.ProductListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *product_grpc.ProductListResponse
	if rf, ok := ret.Get(0).(func(context.Context, *product_grpc.ProductListRequest, ...grpc.CallOption) *product_grpc.ProductListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product_grpc.ProductListResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *product_grpc.ProductListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductServiceClient creates a new instance of ProductServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductServiceClient(t mockConstructorTestingTNewProductServiceClient) *ProductServiceClient {
	mock := &ProductServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
