// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeProductServiceServer is an autogenerated mock type for the UnsafeProductServiceServer type
type UnsafeProductServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedProductServiceServer provides a mock function with given fields:
func (_m *UnsafeProductServiceServer) mustEmbedUnimplementedProductServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeProductServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeProductServiceServer creates a new instance of UnsafeProductServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeProductServiceServer(t mockConstructorTestingTNewUnsafeProductServiceServer) *UnsafeProductServiceServer {
	mock := &UnsafeProductServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
