// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	customer_grpc "github.com/rigmas/microservices/customer/handlers/customer_grpc"
	mock "github.com/stretchr/testify/mock"
)

// CustomerServiceServer is an autogenerated mock type for the CustomerServiceServer type
type CustomerServiceServer struct {
	mock.Mock
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *CustomerServiceServer) Register(_a0 context.Context, _a1 *customer_grpc.RegisterRequest) (*customer_grpc.RegisterResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *customer_grpc.RegisterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *customer_grpc.RegisterRequest) *customer_grpc.RegisterResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer_grpc.RegisterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *customer_grpc.RegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedCustomerServiceServer provides a mock function with given fields:
func (_m *CustomerServiceServer) mustEmbedUnimplementedCustomerServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewCustomerServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerServiceServer creates a new instance of CustomerServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerServiceServer(t mockConstructorTestingTNewCustomerServiceServer) *CustomerServiceServer {
	mock := &CustomerServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
