// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	customer_grpc "github.com/rigmas/microservices/customer/handlers/customer_grpc"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CustomerServiceClient is an autogenerated mock type for the CustomerServiceClient type
type CustomerServiceClient struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *CustomerServiceClient) Register(ctx context.Context, in *customer_grpc.RegisterRequest, opts ...grpc.CallOption) (*customer_grpc.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customer_grpc.RegisterResponse
	if rf, ok := ret.Get(0).(func(context.Context, *customer_grpc.RegisterRequest, ...grpc.CallOption) *customer_grpc.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer_grpc.RegisterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *customer_grpc.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCustomerServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerServiceClient creates a new instance of CustomerServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerServiceClient(t mockConstructorTestingTNewCustomerServiceClient) *CustomerServiceClient {
	mock := &CustomerServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
