// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCustomerServiceServer is an autogenerated mock type for the UnsafeCustomerServiceServer type
type UnsafeCustomerServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCustomerServiceServer provides a mock function with given fields:
func (_m *UnsafeCustomerServiceServer) mustEmbedUnimplementedCustomerServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeCustomerServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeCustomerServiceServer creates a new instance of UnsafeCustomerServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeCustomerServiceServer(t mockConstructorTestingTNewUnsafeCustomerServiceServer) *UnsafeCustomerServiceServer {
	mock := &UnsafeCustomerServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
